version: "2"
services:
  grpcui:
    image: fullstorydev/grpcui:latest
    working_dir: /app
    entrypoint:
      - grpcui
      - -plaintext
      - -bind=0.0.0.0
      - -port=17001
      - -proto=/app/Protos/demo.proto
      - host.docker.internal:5242
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    ports:
      - "17001:17001"